language: python
python:
  - 3.6
before_install:
  - pip install nose
  - pip install coverage
install:
  - python setup.py build
  - python setup.py install
  - python setup.py egg_info
  - pip install -e .
script:
  - coverage run -m nose lightdock/
after_success:
  - bash <(curl -s https://codecov.io/bash)
